cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('current',views.show_cart,name="show-cart"),
    path("history",views.show_carts_history,name="show-carts-history"),
    path('new',views.new_cart,name="new-cart"),
    path('remove/<int:id>',views.remove_item_from_cart,name="remove-item")
]

manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("deliveries",views.show_deliveries_not_deliver_yet,name="show-deliveries-not-deliver-yet"),
    path("deliveries_hitory",views.show_deliveries_history,name="show-deliveries-history"),
    path("delivery_and_order/<int:id>",views.show_delivery_and_order,name="show-delivery-and-order"),
    path("is_delivered/<int:id>",views.is_delivered,name="is-delivered"),
    path("add_category",views.add_category,name="add-category"),
    path("categories",views.show_manager_categories,name="show-manager-categories"),
    path("edit_category/<int:id>",views.edit_category,name="edit-category"),
    path("delete_category/<int:id>",views.delete_category,name="delete-category"),
    path("dishes",views.show_manager_dishes,name="show-manager-dishes"),
    path("add_dish",views.add_dish,name="add-dish"),
    path("edit_dish/<int:id>",views.edit_dish,name="edit-dish"),
    path("delete_dish/<int:id>",views.delete_dish,name="delete-dish")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('user.urls')),
    path("categories/",include('category.urls')),
    path("cart/",include('cart.urls')),
    path("dish/",include('dish.urls')),
    path("delivery/",include('delivery.urls')),
    path("manager/",include('manager.urls'))
]

dish/models.py
from django.db import models
from django.core.validators import MinValueValidator
from category.models import Category

# Create your models here.
class Dish(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    description = models.TextField(blank=True)
    image = models.TextField(blank=True)
    is_gluten_free = models.BooleanField()
    is_vegeterian = models.BooleanField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)


    def __str__(self):
        return self.name

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms  

class CategoryForm(forms.Form):
    name = forms.CharField(label="Category Name",max_length=200,min_length=1,required=True)
    image = forms.CharField(widget=forms.Textarea,required=False)




class DishForm(forms.Form):
    name = forms.CharField(label="Dish Name",max_length=200,min_length=1,required=True)
    price = forms.IntegerField(min_value=1,required=True)
    description = forms.CharField(widget=forms.Textarea,required=False)
    image = forms.CharField(widget=forms.Textarea,required=False)
    is_gluten_free = forms.BooleanField(required=False)
    is_vegeterian = forms.BooleanField(required=False)

manager/views.py
from django.shortcuts import render,redirect
from dish.models import Dish
from delivery.models import Delivery
from cart.models import Cart
from items.models import Item
from category.models import Category
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, DishForm
from django.contrib import messages
# Create your views here.

def category_name_not_unique(category_name):
    if Category.objects.filter(name=category_name):
        return True
    return False 


@login_required(login_url="login-manager")
def show_deliveries_not_deliver_yet(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    deliveries = Delivery.objects.all()
    return render(request,'manager/delivers_not_deliver_yet.html',{"deliveries":deliveries})


@login_required(login_url="login-manager")
def show_deliveries_history(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    deliveries = Delivery.objects.all()
    return render(request,'manager/deliveries_history.html',{"deliveries":deliveries[::-1]})



@login_required(login_url="login-manager")
def show_delivery_and_order(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    delivery = Delivery.objects.get(order_id=id)
    cart = Cart.objects.get(id=id)
    items = Item.objects.filter(cart_id=cart.id)
    total_raw_list = []
    total_sum = 0
    for item in items:
        total_sum += int(item.amount) * int(item.dish.price)
        total_raw_list.append(int(item.amount) * int(item.dish.price))
    items_and_total_raw_list = zip(items,total_raw_list)
    return render(request,'manager/order_and_delivery.html',
                  {"delivery":delivery,"items_and_total_raw_list":items_and_total_raw_list,"total_sum":total_sum})


@login_required(login_url="login-manager")
def is_delivered(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    delivery = Delivery.objects.get(order_id=id)
    if request.method == "POST":
        delivery.is_delivered = True
        delivery.save()
        return redirect('show-deliveries-history')


@login_required(login_url="login-manager")
def add_category(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            if category_name_not_unique(form.cleaned_data['name']):
                 messages.error(request,f"A category with that name already exists - {form.cleaned_data['name']}")
                 return redirect("add-category")
            new_category = Category(
                name = form.cleaned_data['name'],
                image = form.cleaned_data['image']
            )
            new_category.save()
            messages.success(request,f"New Category added - {form.cleaned_data['name']}")
            return redirect("show-manager-categories")
    else:
        form = CategoryForm()
    return render(request,"manager/add_category.html",{"form":form})



@login_required(login_url="login-manager")
def show_manager_categories(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    categories = Category.objects.all()
    return render(request,"manager/manager_categories.html",{"categories":categories})


@login_required(login_url="login-manager")
def delete_category(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')

    category = Category.objects.get(id=id)
    if request.method == "POST":
        category.delete()
        return redirect('show-manager-categories')
    


@login_required(login_url="login-manager")
def edit_category(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    category = Category.objects.get(id=id)
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            if category_name_not_unique(form.cleaned_data['name']):
                 messages.error(request,f"A category with that name already exists - {form.cleaned_data['name']}")
                 return redirect("edit-category",id = category.id)
            category.name = form.cleaned_data['name']
            category.image = form.cleaned_data['image']
            category.save()
            messages.success(request,f"Category edited successfully - {form.cleaned_data['name']}")
            return redirect("show-manager-categories")
    else:
        form = CategoryForm()
    return render(request,"manager/edit_category.html",{"form":form,"category":category})
    


@login_required(login_url="login-manager")
def show_manager_dishes(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    categories = Category.objects.all()
    return render(request,"manager/manager_dishes.html",{"categories":categories})


@login_required(login_url="login-manager")
def add_dish(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    categories = Category.objects.all()
    if request.method == "POST":
        is_gluten_free = request.POST.get('is_gluten_free') == 'on'
        is_vegeterian = request.POST.get('is_vegeterian') == 'on'
        if not request.POST.get('category_id'):
             messages.error(request,f"You must choose category to the new dish!")
             return redirect("add-dish")

        form = DishForm(request.POST)
        if form.is_valid():
            new_dish = Dish(
                name = form.cleaned_data['name'],
                price = form.cleaned_data['price'],
                description = form.cleaned_data['description'],
                image = form.cleaned_data['image'],
                is_gluten_free = is_gluten_free,
                is_vegeterian = is_vegeterian,
                category_id = request.POST['category_id']

            )
            new_dish.save()
            messages.success(request,f"New Dish added - {form.cleaned_data['name']}")
            return redirect("show-manager-dishes")
    else:
        form = DishForm()
    return render(request,"manager/add_dish.html",{"form":form,"categories":categories})



@login_required(login_url="login-manager")
def delete_dish(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')

    dish = Dish.objects.get(id=id)
    if request.method == "POST":
        dish.delete()
        return redirect('show-manager-dishes')
    


@login_required(login_url="login-manager")
def edit_dish(request,id):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('show-categories')
    
    dish = Dish.objects.get(id=id)
    categories = Category.objects.all()
    if request.method == "POST":
        is_gluten_free = request.POST.get('is_gluten_free') == 'on'
        is_vegeterian = request.POST.get('is_vegeterian') == 'on'
        if not request.POST.get('category_id'):
             messages.error(request,f"You must choose category when you edit a dish!")
             return redirect("edit-dish",id=dish.id)
        form = DishForm(request.POST)
        if form.is_valid():
            dish.name = form.cleaned_data['name']
            dish.price = form.cleaned_data['price']
            dish.description = form.cleaned_data['description']
            dish.image = form.cleaned_data['image']
            dish.is_gluten_free = is_gluten_free
            dish.is_vegeterian = is_vegeterian
            dish.save()
            messages.success(request,f"Dish edited successfully - {form.cleaned_data['name']}")
            return redirect("show-manager-dishes")
    else:
        form = DishForm()
    return render(request,"manager/edit_dish.html",{"form":form,"dish":dish,"categories":categories})

manager/templates/manager/add_category.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}
<h1 style="text-align: center;">Add Category</h1>
<div class="container">
    <ul>   
        {% for message in messages %}  
                    <li style="color: red; font-weight: bold">{{ message }}</li>  
        {% endfor %}  
    </ul>  
    <form class="col s12" action="{% url 'add-category' %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="name" placeholder="Category Name">
                {% for error in form.name.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <textarea name="image" placeholder="Image Relative Path"></textarea>
            </div>
            <button type="submit" class="waves-effect waves-light btn">Add Category</button>
        </div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/add_dish.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}
<h1 style="text-align: center;">Add Dish</h1>
<div class="container"> 
    <ul>   
        {% for message in messages %}  
                    <li style="color: red; font-weight: bold">{{ message }}</li>  
        {% endfor %}  
    </ul> 
    <form class="col s12" action="{% url 'add-dish' %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="name" placeholder="Dish Name">
                {% for error in form.name.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <input type="number" name="price" placeholder="Price" min="1">
                {% for error in form.price.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <textarea name="description" placeholder="Description"></textarea>
            </div>
            <div class="input-field col s12">
                <textarea name="image" placeholder="Image Relative Path"></textarea>
            </div>
            <p>
                <label>
                  <input type="checkbox" class="filled-in" name="is_gluten_free"/>
                  <span>Is Gluten Free</span>
                </label>
            </p>
            <p>
                <label>
                  <input type="checkbox" class="filled-in" name="is_vegeterian"/>
                  <span>Is Vegeterian</span>
                </label>
            </p>
            <select class="browser-default" name="category_id" >
              <option value="" disabled selected>Choose Dish Category</option>
              {% for category in categories %}
              <option value="{{category.id}}">{{category.name}}</option>
              {% endfor %}
            </select>
            <button type="submit" class="waves-effect waves-light btn">Add Dish</button>
        </div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/deliveries_history.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}

<h1 style="text-align: center;"> Deliveries Details</h1>

<div class="container">
    <table class="striped centered">
        <thead>
          <tr>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Order ID</th>
              <th>Address</th>
              <th>Comment</th>
              <th>Created</th>
              <th>Is Delivered</th>
              <th>Order Details</th>
          </tr>
        </thead>
        <tbody>
            {% for delivery in deliveries %}
                {% if delivery.is_delivered %}
                    <tr style="background-color: aquamarine;">
                        <td>{{delivery.order_id.user.username}}</td>
                        <td>{{delivery.order_id.user.first_name}}</td>
                        <td>{{delivery.order_id.user.last_name}}</td>
                        <td>{{delivery.order_id.id}}</td>
                        <td>{{delivery.address}}</td>
                        <td>{{delivery.comment | linebreaks}}</td>
                        <td>{{delivery.created | date:"d/m/Y H:i"}}</td>
                        <td>Yes</td>
                        <td>
                            <form action="{% url 'show-delivery-and-order' id=delivery.order_id.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Order details</button>  
                            </form>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

manager/templates/manager/delivers_not_deliver_yet.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}

<h1 style="text-align: center;"> Deliveries Details</h1>

<div class="container">
    <table class="striped centered">
        <thead>
          <tr>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Order ID</th>
              <th>Address</th>
              <th>Comment</th>
              <th>Created</th>
              <th>Is Delivered</th>
              <th>Order Details</th>
          </tr>
        </thead>
        <tbody>
            {% for delivery in deliveries %}
                {% if delivery.is_delivered == False %}
                    <tr style="background-color: tomato;">
                        <td>{{delivery.order_id.user.username}}</td>
                        <td>{{delivery.order_id.user.first_name}}</td>
                        <td>{{delivery.order_id.user.last_name}}</td>
                        <td>{{delivery.order_id.id}}</td>
                        <td>{{delivery.address}}</td>
                        <td>{{delivery.comment | linebreaks}}</td>
                        <td>{{delivery.created | date:"d/m/Y H:i"}}</td>
                        <td>No</td>
                        <td>
                            <form action="{% url 'show-delivery-and-order' id=delivery.order_id.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Order details and delivery</button>  
                            </form>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

manager/templates/manager/edit_category.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}
<h1 style="text-align: center;">Edit Category</h1>
<div class="container">
    <ul>   
        {% for message in messages %}  
                    <li style="color: red; font-weight: bold">{{ message }}</li>  
        {% endfor %}  
    </ul>  
    <form class="col s12" action="{% url 'edit-category' id=category.id %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input id="category_name" type="text" name="name" value="{{category.name}}">
                <label for="category_name">Category Name</label>
                {% for error in form.name.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <textarea id="category_image" name="image" placeholder="Image Relative Path">{{category.image}}</textarea>
                <label for="category_image">Image Relative Path</label>
            </div>
            <button type="submit" class="waves-effect waves-light btn">Edit Category</button>
        </div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/edit_dish.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}
<h1 style="text-align: center;">Edit Dish</h1>
<div class="container"> 
    <ul>   
        {% for message in messages %}  
                    <li style="color: red; font-weight: bold">{{ message }}</li>  
        {% endfor %}  
    </ul> 
    <form class="col s12" action="{% url 'edit-dish' id=dish.id %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input type="text" id="dish_name" name="name" placeholder="Dish Name" value="{{dish.name}}">
                <label for="dish_name">Dish Name</label>
                {% for error in form.name.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <input type="number" id="price" name="price" placeholder="Price" min="1" value="{{dish.price}}">
                <label for="price">Price</label>
                {% for error in form.price.errors %}
                    <div>{{error}}</div><br>
                {% endfor %}
            </div>
            <div class="input-field col s12">
                <textarea name="description" id="description" placeholder="Description">{{dish.description}}</textarea>
                <label for="description">Description</label>
            </div>
            <div class="input-field col s12">
                <textarea name="image" id="image" placeholder="Image Relative Path">{{dish.image}}</textarea>
                <label for="image">Image Relative Path</label>
            </div>
            <p>
                <label>
                  <input type="checkbox" class="filled-in" name="is_gluten_free" {% if dish.is_gluten_free %} checked {% endif %}/>
                  <span>Is Gluten Free</span>
                </label>
            </p>
            <p>
                <label>
                  <input type="checkbox" class="filled-in" name="is_vegeterian" {% if dish.is_vegeterian %} checked {% endif %}/>
                  <span>Is Vegeterian</span>
                </label>
            </p>
            <select class="browser-default" name="category_id" >
              <option value="" disabled selected>Choose Dish Category</option>
              {% for category in categories %}
              <option value="{{category.id}}">{{category.name}}</option>
              {% endfor %}
            </select>
            <button type="submit" class="waves-effect waves-light btn">Edit Dish</button>
        </div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/manager_categories.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}

<h1 style="text-align: center;"> Edit and Delete Categories</h1>

<div class="container">
    <ul>   
        {% for message in messages %}  
            {% if 'success' == message.tags %}  
                    <li style="color: green; font-weight: bold">{{ message }}</li>    
            {% endif %} 
        {% endfor %}  
    </ul> 
    <table class="striped centered">
        <thead>
          <tr>
              <th>Category Name</th>
              <th>Image</th>
              <th>Edit Category</th>
              <th>Delete Category</th>
          </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                    <tr>
                        <td>{{category.name}}</td>
                        <td><img src="{{category.image}}" alt="{{category.name}}"></td>
                        <td>
                            <form action="{% url 'edit-category' id=category.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Edit</button>  
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'delete-category' id=category.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Delete</button>  
                            </form>
                        </td>
                    </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

manager/templates/manager/manager_dishes.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}

<h1 style="text-align: center;"> Edit and Delete Dishes</h1>

<div class="container">
    <ul>   
        {% for message in messages %}  
            {% if 'success' == message.tags %}  
                    <li style="color: green; font-weight: bold">{{ message }}</li>    
            {% endif %} 
        {% endfor %}  
    </ul> 
    <table class="striped centered">
        <thead>
          <tr>
              <th>Category Name</th>
              <th>Dish Name</th>
              <th>Price</th>
              <th>Description</th>
              <th>Dish Image</th>
              <th>Is Gluten Free</th>
              <th>Is Vegeterian</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                {% for dish in category.dish_set.all %}
                    <tr>
                        <td>{{category.name}}</td>
                        <td>{{dish.name}}</td>
                        <td>{{dish.price}}$</td>
                        <td>{{dish.description | linebreaks}}</td>
                        <td><img src="{{dish.image}}" alt="{{dish.name}}"></td>
                        {% if dish.is_gluten_free %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                        {% if dish.is_vegeterian %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                        <td>
                            <form action="{% url 'edit-dish' id=dish.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Edit</button>  
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'delete-dish' id=dish.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn">Delete</button>  
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

manager/templates/manager/order_and_delivery.html
{%extends 'layouts/layout.html'%}
{% block content %}
{% include 'common/navbar_manager.html' %}

<h1 style="text-align: center;"> Deliveries Details</h1>

<div class="container">
    <table class="striped centered">
        <thead>
          <tr>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Order ID</th>
              <th>Address</th>
              <th>Comment</th>
              <th>Created</th>
              <th>Is Delivered</th>
              <th>Delivery</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{delivery.order_id.user.username}}</td>
            <td>{{delivery.order_id.user.first_name}}</td>
            <td>{{delivery.order_id.user.last_name}}</td>
            <td>{{delivery.order_id.id}}</td>
            <td>{{delivery.address}}</td>
            <td>{{delivery.comment | linebreaks}}</td>
            <td>{{delivery.created | date:"d/m/Y H:i"}}</td>
            {% if delivery.is_delivered %}
            <td>Yes</td>
            {% else %}
            <td>No</td>
            {% endif %}
            <td>
                <form action="{% url 'is-delivered' id=delivery.order_id.id %}" method="POST">
                    {% csrf_token %}
                    <button {% if delivery.is_delivered %} disabled {% endif %} type="submit" class="waves-effect waves-light btn">To Delivery</button>  
                </form>
            </td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <table class="striped centered" style="border: 1px solid black;">
        <thead>
          <tr>
              <th>Name</th>
              <th>Image</th>
              <th>Price Per Unit</th>
              <th>Amount</th>
              <th>Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for item,total_raw in items_and_total_raw_list %}
          <tr>
            <td>{{item.dish.name}}</td>
            <td><img src="{{item.dish.image}}"></td>
            <td>{{item.dish.price}}$</td>
            <td>{{item.amount}}</td>
            <td>{{total_raw}}$</td>
          </tr>
          {% endfor %}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Sum: {{total_sum}}$</td>
          </tr>
        </tbody>
      </table>
</div>
{% endblock content %}